name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: [
           "pip-test"
        ]
        baseImage:
          [
            "mcr.microsoft.com/devcontainers/base:ubuntu-22.04"
          ]
    steps:
      - uses: actions/checkout@v2

      # - name: "Install latest devcontainer CLI"
      #   run: npm install -g @devcontainers/cli

      - name: "Install latest devcontainer CLI"
        run: |
          git clone --depth 1 --branch main https://github.com/devcontainers/cli.git &&
          cd cli &&
          yarn &&
          yarn compile &&
          npm link

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      # - name: "Install latest devcontainer CLI"
      #   run: npm install -g @devcontainers/cli

      - name: "Install latest devcontainer CLI"
        run: |
          git clone --depth 1 --branch main https://github.com/devcontainers/cli.git &&
          cd cli &&
          yarn &&
          yarn compile &&
          npm link

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
